### ISSUE TITLE
Hashing algorithm

### ISSUE THREAD

**Issue by alinnow** [semibreve/minim#1]
Hey, nice project. I understand the motivation as I run a few self-hosted things just for myself, too. Only one of them runs on PHP though. I could still give this a try for that.

I would suggest switching to bcrypt for your hashing algorithm though, as it's designed for password hashing with a work factor that can be increased as computers get faster. Most likely it's not actually a concern for one account's password on some self-hosted applications, but IMO it's worth trying to use the best things for hobby projects 😉.

PHP has a built-in set of functions (as of 5.5): http://php.net/password. There is also a library for backwards compatibility if needed: https://github.com/ircmaxell/password_compat. Read http://blog.ircmaxell.com/2012/12/seven-ways-to-screw-up-bcrypt.html to make sure you're doing it right 😄

**Comment by lambdacasserole** [comment]
Made a change in pull request #2 that addresses this, good advice, thank you. Feel free to glance over the PR if you have a moment Alan.

**Comment by lambdacasserole** [comment]
Just merged #2 with the suggested changes, including wrapper script and updated docs.
